# Generated by Django 6.0.3 on 2026-03-26 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('url', models.URLField(blank=True, help_text='External link to the resource')),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('guide', 'Implementation Guide'), ('research', 'Research Paper'), ('tool', 'Tool / Template'), ('video', 'Video'), ('webinar', 'Webinar Recording'), ('other', 'Other')], default='article', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
                ('problem_statements', models.ManyToManyField(blank=True, help_text='Related literacy challenges', related_name='resources', to='community.problemstatement')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
