# Generated by Django 6.0.3 on 2026-03-26 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('nces_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('district_type', models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural'), ('town', 'Town')], max_length=20)),
                ('size_category', models.CharField(choices=[('small', 'Small (Under 1,000)'), ('medium', 'Medium (1,000–5,000)'), ('large', 'Large (5,000–25,000)'), ('very_large', 'Very Large (25,000+)')], max_length=20)),
                ('enrollment', models.IntegerField(default=0)),
                ('free_reduced_lunch_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('esl_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('curriculum', 'Curriculum & Instruction'), ('assessment', 'Assessment & Data'), ('professional_dev', 'Professional Development'), ('equity', 'Equity & Access'), ('leadership', 'Leadership & Culture')], max_length=30)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='e.g. Curriculum Director', max_length=100)),
                ('years_experience', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='community.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('problem_statements', models.ManyToManyField(blank=True, related_name='members', to='community.problemstatement')),
            ],
        ),
    ]
